###

GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3VkaGkiLCJpYXQiOjE3MDU3MjI4OTZ9.8KGJuIosdMWPJvlZinh8-F4sz8OoUO_My77f1rhNxvw

###

GET http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3VkaGkiLCJpYXQiOjE3MDU3MjI4OTZ9.8KGJuIosdMWPJvlZinh8-F4sz8OoUO_My77f1rhNxvw

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"sudhi"
}